sudo: required
language: python
services:
    - docker
cache: pip
install: pip install docker-compose
script:
    - docker-compose build
    - docker-compose run --rm pytest cat 123
    - echo $?
    - docker rmi $(docker images -q)
